version: "3.6"

services:
  php:
    restart: always
    build:
      context: ./config
      dockerfile: php.dev.dockerfile
    depends_on:
      - db
    volumes:
      - "./app:/var/www/html"
    user: ngozi_dev_api_user
