name: Development CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # unit_test:
  #   name: "Run Unit Tests"
  #   runs-on: ubuntu-latest

  #   services:
  #     mariadb:
  #       image: mariadb:latest
  #       ports:
  #         - 3306
  #       env:
  #         MYSQL_DATABASE: delivr
  #         MYSQL_ROOT_PASSWORD: testpassword888
  #       options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Setup environment
  #       working-directory: ./app
  #       run: |
  #         cp .env.unit-test .env

  #     - name: Install Composer dependencies
  #       working-directory: ./app
  #       run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

  #     - name: Execute tests via PHPUnit
  #       env:
  #         DB_PORT: ${{ job.services.mariadb.ports[3306] }}
  #       working-directory: ./app
  #       run: |
  #         php artisan key:generate
  #         php artisan test

  deploy:
    name: Deploy to dev server
    runs-on: ubuntu-latest
    needs: [unit_test]

    steps:
      - name: Execute commands via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.dev_host }}
          username: ${{ secrets.dev_username }}
          key: ${{ secrets.dev_private_key }}
          port: 22
          script: |
            cd /srv/dev/ngozi-awards-api
            git pull
            git reset --hard HEAD

            docker-compose exec -T php composer install
            docker-compose exec -T php php artisan config:clear
            docker-compose exec -T php php artisan route:clear
            docker-compose exec -T php php artisan view:clear
            docker-compose exec -T php php artisan cache:clear
            docker-compose exec -T php php artisan migrate

            docker-compose restart queue
            docker-compose up -d
